function [q_sp1,q_sp2] = RR_EndEffector(l1,l2,th1,th2)
%RR_ENDEFFECTOR
%    [Q_SP1,Q_SP2] = RR_ENDEFFECTOR(L1,L2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Apr-2020 23:37:38

t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = l1.*t2;
t6 = l1.*t3;

% q_sp1 = [t5;t6;0.0;1.0];
% if nargout > 1
%     q_sp2 = [t5+l2.*cos(t4);t6+l2.*sin(t4);0.0;1.0];
% end

num = length(th1);
Zero = zeros(num,1);
One = ones(num,1);

q_sp1 = [t5 t6 Zero One];
if nargout > 1
    q_sp2 = [t5+l2.*cos(t4) t6+l2.*sin(t4) Zero One];
end